import type { Species } from "@/lib/types";

/**
 * Curated spider species library. Doubles as the home "showcase" data and the
 * offline fallback for /species when Supabase is not yet configured.
 */
export const speciesLibrary: Species[] = [
  {
    slug: "common-house-spider",
    common_name: "Common House Spider",
    scientific_name: "Parasteatoda tepidariorum",
    family: "Theridiidae (cobweb weavers)",
    venom_level: "harmless",
    size: "Body 5–8 mm",
    region: "Worldwide",
    habitat: "Corners of rooms, garages, sheds and window frames.",
    summary:
      "The spider you most often meet indoors. It builds tangled cobwebs in quiet corners and is completely harmless to people.",
    identification: [
      "Round, bulbous abdomen with mottled brown and cream patterning",
      "Builds an irregular tangle web (cobweb), not a neat orb",
      "Long, thin legs banded with light and dark rings",
      "Often seen hanging upside-down in its web",
    ],
    fact: "A single female can produce up to 17 egg sacs in her lifetime, each holding 100+ eggs.",
    accent: "gold",
  },
  {
    slug: "black-widow",
    common_name: "Black Widow",
    scientific_name: "Latrodectus mactans",
    family: "Theridiidae (cobweb weavers)",
    venom_level: "dangerous",
    size: "Body 8–13 mm (female)",
    region: "Americas, temperate worldwide",
    habitat: "Woodpiles, sheds, undisturbed dark spaces and garden debris.",
    summary:
      "Glossy black with the unmistakable red hourglass. Its neurotoxic venom makes it the most medically significant spider in North America.",
    identification: [
      "Shiny jet-black globular abdomen",
      "Red (or orange) hourglass mark on the underside",
      "Messy, strong, irregular web close to the ground",
      "Female much larger than the male",
    ],
    fact: "Black widow venom is roughly 15× more potent drop-for-drop than a rattlesnake's, but the dose delivered is tiny.",
    accent: "crimson",
    is_dangerous: true,
  },
  {
    slug: "brown-recluse",
    common_name: "Brown Recluse",
    scientific_name: "Loxosceles reclusa",
    family: "Sicariidae",
    venom_level: "dangerous",
    size: "Body 6–11 mm",
    region: "Central & southern United States",
    habitat: "Closets, attics, cardboard boxes and rarely disturbed storage.",
    summary:
      "A shy, reclusive hunter recognised by the dark violin shape on its back. Its cytotoxic venom can cause slow-healing wounds.",
    identification: [
      "Violin-shaped marking pointing toward the abdomen",
      "Six eyes arranged in three pairs (most spiders have eight)",
      "Uniform tan to brown colour with no leg banding",
      "Smooth legs, no spines",
    ],
    fact: "Unlike most spiders, the brown recluse has six eyes in three pairs — a key AI identification signal.",
    accent: "crimson",
    is_dangerous: true,
  },
  {
    slug: "jumping-spider",
    common_name: "Bold Jumping Spider",
    scientific_name: "Phidippus audax",
    family: "Salticidae (jumping spiders)",
    venom_level: "harmless",
    size: "Body 8–19 mm",
    region: "North America",
    habitat: "Sunny walls, fences, gardens and window sills.",
    summary:
      "Charismatic, curious and fuzzy, with huge forward-facing eyes. It hunts by pouncing rather than building webs.",
    identification: [
      "Two enormous central eyes for sharp, colour vision",
      "Compact, hairy body — often black with a white or orange spot",
      "Iridescent green or blue chelicerae (fangs)",
      "Moves in quick hops, frequently turns to 'look' at you",
    ],
    fact: "Jumping spiders can see a wider range of colour than humans and even perceive some ultraviolet light.",
    accent: "gold",
  },
  {
    slug: "golden-silk-orb-weaver",
    common_name: "Golden Silk Orb-Weaver",
    scientific_name: "Trichonephila clavipes",
    family: "Araneidae (orb weavers)",
    venom_level: "mild",
    size: "Body 24–40 mm (female)",
    region: "Southern US, Central & South America",
    habitat: "Forest edges and clearings, spanning large webs between trees.",
    summary:
      "Spins enormous webs of shimmering golden silk. Large and dramatic, yet shy and reluctant to bite.",
    identification: [
      "Silk that glints distinctly gold in sunlight",
      "Elongated silver-and-yellow abdomen",
      "Feathery tufts of hair on the leg joints",
      "Very large female; tiny, easily missed male",
    ],
    fact: "Its golden silk is among the toughest natural fibres known — stronger by weight than steel.",
    accent: "gold",
  },
  {
    slug: "garden-orb-weaver",
    common_name: "European Garden Spider",
    scientific_name: "Araneus diadematus",
    family: "Araneidae (orb weavers)",
    venom_level: "harmless",
    size: "Body 6–20 mm",
    region: "Europe, North America",
    habitat: "Gardens, hedgerows and tall grass; classic dewy autumn webs.",
    summary:
      "The textbook orb-weaver. Famous for the pale cross of dots on its back and its perfectly engineered circular web.",
    identification: [
      "White cross-shaped pattern of spots on the abdomen",
      "Builds a large, near-perfect wheel-shaped orb web",
      "Colour ranges from light tan to deep rust-brown",
      "Rebuilds its web almost every night",
    ],
    fact: "It often eats its own web each evening and recycles the protein to spin a fresh one.",
    accent: "gold",
  },
  {
    slug: "cellar-spider",
    common_name: "Daddy Long-Legs (Cellar Spider)",
    scientific_name: "Pholcus phalangioides",
    family: "Pholcidae",
    venom_level: "harmless",
    size: "Body 7–10 mm, legs to 50 mm",
    region: "Worldwide",
    habitat: "Cellars, ceilings, garages and other cool, dark corners.",
    summary:
      "Impossibly thin legs and a small body. When threatened it vibrates its web into a blur to confuse predators.",
    identification: [
      "Extremely long, fragile, thread-like legs",
      "Small peanut-shaped greyish body",
      "Loose, messy web in ceiling corners",
      "Whirls rapidly when disturbed",
    ],
    fact: "The myth that it has the deadliest venom but can't bite is false — its venom is simply very weak.",
    accent: "gold",
  },
  {
    slug: "wolf-spider",
    common_name: "Wolf Spider",
    scientific_name: "Hogna / Lycosa species",
    family: "Lycosidae (wolf spiders)",
    venom_level: "mild",
    size: "Body 10–35 mm",
    region: "Worldwide",
    habitat: "Ground level — lawns, leaf litter, fields and basements.",
    summary:
      "A fast, robust ground hunter that chases prey instead of trapping it. Intimidating in size but rarely a threat.",
    identification: [
      "Stocky, hairy, earth-toned body for camouflage",
      "Two of its eight eyes are large and forward-facing",
      "Carries its egg sac attached to the spinnerets",
      "Eyes reflect a bright greenish shine in torchlight",
    ],
    fact: "A mother wolf spider carries dozens of spiderlings on her back until they are ready to disperse.",
    accent: "gold",
  },
  {
    slug: "hobo-spider",
    common_name: "Hobo Spider",
    scientific_name: "Eratigena agrestis",
    family: "Agelenidae (funnel weavers)",
    venom_level: "caution",
    size: "Body 8–18 mm",
    region: "Pacific Northwest US, Europe",
    habitat: "Ground-level funnel webs in cracks, window wells and foundations.",
    summary:
      "A fast funnel-web builder often confused with more dangerous species. Bites are uncommon and usually mild.",
    identification: [
      "Funnel-shaped retreat web near ground level",
      "Brown body with a faint herringbone pattern on the abdomen",
      "Long legs without distinct dark bands",
      "Runs very quickly when disturbed",
    ],
    fact: "Despite an old reputation, current research finds little evidence the hobo spider causes serious wounds.",
    accent: "crimson",
  },
  {
    slug: "huntsman-spider",
    common_name: "Huntsman Spider",
    scientific_name: "Heteropoda venatoria",
    family: "Sparassidae",
    venom_level: "mild",
    size: "Leg span up to 150 mm",
    region: "Tropical & subtropical worldwide",
    habitat: "Under bark, on walls and ceilings, frequently indoors in warm climates.",
    summary:
      "Large, flat and lightning fast. Its legs splay crab-like, letting it squeeze under bark and into tight gaps.",
    identification: [
      "Huge, flattened body with legs that twist forward, crab-like",
      "Mottled grey-brown camouflage",
      "Moves sideways with startling speed",
      "Does not build a capture web",
    ],
    fact: "A huntsman can cover a metre in under a second — useful camouflage hunting at night.",
    accent: "gold",
  },
  {
    slug: "brazilian-wandering-spider",
    common_name: "Brazilian Wandering Spider",
    scientific_name: "Phoneutria species",
    family: "Ctenidae",
    venom_level: "dangerous",
    size: "Body up to 50 mm, leg span 180 mm",
    region: "Central & South America",
    habitat: "Forest floors by night; hides in vegetation, logs and bananas by day.",
    summary:
      "An aggressive, restless hunter and one of the most venomous spiders in the world. Strictly look-don't-touch.",
    identification: [
      "Raises its front legs high in a defensive display",
      "Large, robust body with reddish jaws (chelicerae)",
      "Does not build a web — wanders to hunt",
      "Bands of light spots along the underside of the legs",
    ],
    fact: "When threatened it rears up on its back legs, exposing the red hairs around its fangs as a warning.",
    accent: "crimson",
    is_dangerous: true,
  },
  {
    slug: "tarantula",
    common_name: "Tarantula",
    scientific_name: "Theraphosidae family",
    venom_level: "caution",
    family: "Theraphosidae",
    size: "Leg span 100–280 mm",
    region: "Americas, Africa, Asia, Australia",
    habitat: "Burrows, tree hollows and ground retreats in warm regions.",
    summary:
      "The giants of the spider world. Imposing and hairy, but most species are docile with venom no worse than a bee sting.",
    identification: [
      "Very large, heavy, densely hairy body and legs",
      "Slow, deliberate movement",
      "New-world species flick irritating hairs when threatened",
      "Lives for years — females of some species over 20 years",
    ],
    fact: "A tarantula's bald patch on the abdomen shows where it has kicked off defensive urticating hairs.",
    accent: "gold",
  },
];

export function getSpeciesBySlug(slug: string) {
  return speciesLibrary.find((s) => s.slug === slug);
}
